import {
  TRADING_DIALECTIC_KIND,
  TRADING_DIALECTIC_VERSION,
} from "./types.js";

const NonEmptyString = { type: "string", minLength: 1 } as const;
const Score01 = { type: "number", minimum: 0, maximum: 1 } as const;

const SharedDefs = {
  agentRef: {
    type: "object",
    additionalProperties: false,
    required: ["agentId"],
    properties: {
      agentId: NonEmptyString,
      sessionKey: NonEmptyString,
      nodeId: NonEmptyString,
    },
  },
  hardVetoCode: {
    type: "string",
    enum: [
      "stale_data",
      "exchange_incident",
      "risk_budget_violation",
      "timestamp_drift",
      "execution_path_error",
    ],
  },
  verdict: {
    type: "string",
    enum: ["EXECUTE_FULL", "EXECUTE_PROBE", "WAIT_TRIGGER", "ABSTAIN", "VETO"],
  },
  meta: {
    type: "object",
    additionalProperties: false,
    required: [
      "symbol",
      "venue",
      "marketType",
      "side",
      "accountRef",
      "timeHorizon",
      "urgency",
      "snapshotAt",
      "dataFreshnessMs",
      "openedAt",
      "expiresAt",
      "openedBy",
    ],
    properties: {
      symbol: NonEmptyString,
      venue: NonEmptyString,
      marketType: { type: "string", enum: ["spot", "perp", "futures", "options"] },
      side: { type: "string", enum: ["long", "short"] },
      accountRef: NonEmptyString,
      timeHorizon: { type: "string", enum: ["scalp", "intraday", "swing", "position"] },
      urgency: { type: "string", enum: ["low", "normal", "high"] },
      strategyId: NonEmptyString,
      riskBudgetRef: NonEmptyString,
      snapshotAt: NonEmptyString,
      dataFreshnessMs: { type: "integer", minimum: 0 },
      openedAt: NonEmptyString,
      expiresAt: NonEmptyString,
      openedBy: NonEmptyString,
    },
  },
  context: {
    type: "object",
    additionalProperties: false,
    required: ["marketSnapshot"],
    properties: {
      marketSnapshot: { type: "object" },
      contextRefs: { type: "array", items: NonEmptyString },
      maxProbeRiskR: { type: "number", minimum: 0 },
      maxFullRiskR: { type: "number", minimum: 0 },
      maxLeverage: { type: "number", minimum: 0 },
      maxTimestampDriftMs: { type: "integer", minimum: 0 },
    },
  },
  thesis: {
    type: "object",
    additionalProperties: false,
    required: [
      "author",
      "submittedAt",
      "regimeHypothesis",
      "tradeIdea",
      "whyNow",
      "entryPlan",
      "invalidation",
      "targets",
      "confidence",
      "evidenceRefs",
      "assumptions",
      "riskNotes",
    ],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      submittedAt: NonEmptyString,
      regimeHypothesis: NonEmptyString,
      tradeIdea: NonEmptyString,
      whyNow: NonEmptyString,
      entryPlan: NonEmptyString,
      invalidation: NonEmptyString,
      targets: { type: "array", items: NonEmptyString },
      confidence: Score01,
      evidenceRefs: { type: "array", items: NonEmptyString },
      assumptions: { type: "array", items: NonEmptyString },
      riskNotes: { type: "array", items: NonEmptyString },
    },
  },
  antithesis: {
    type: "object",
    additionalProperties: false,
    required: [
      "author",
      "submittedAt",
      "counterView",
      "alternativeRegime",
      "whyThesisMayFail",
      "failureModes",
      "contradictions",
      "vetoFlags",
      "evidenceRefs",
      "confidence",
    ],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      submittedAt: NonEmptyString,
      counterView: NonEmptyString,
      alternativeRegime: NonEmptyString,
      whyThesisMayFail: NonEmptyString,
      failureModes: { type: "array", items: NonEmptyString },
      contradictions: { type: "array", items: NonEmptyString },
      vetoFlags: { type: "array", items: { $ref: "#/$defs/hardVetoCode" } },
      evidenceRefs: { type: "array", items: NonEmptyString },
      confidence: Score01,
    },
  },
  rebuttal: {
    type: "object",
    additionalProperties: false,
    required: [
      "author",
      "submittedAt",
      "response",
      "defendedClaims",
      "concededRisks",
      "residualRisks",
    ],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      submittedAt: NonEmptyString,
      response: NonEmptyString,
      defendedClaims: { type: "array", items: NonEmptyString },
      concededRisks: { type: "array", items: NonEmptyString },
      residualRisks: { type: "array", items: NonEmptyString },
    },
  },
  synthesis: {
    type: "object",
    additionalProperties: false,
    required: [
      "author",
      "submittedAt",
      "preserve",
      "discard",
      "metaRule",
      "verdict",
      "triggerSet",
      "sizeRule",
      "killSwitch",
      "unresolved",
    ],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      submittedAt: NonEmptyString,
      preserve: { type: "array", items: NonEmptyString },
      discard: { type: "array", items: NonEmptyString },
      metaRule: NonEmptyString,
      verdict: { $ref: "#/$defs/verdict" },
      triggerSet: { type: "array", items: NonEmptyString },
      sizeRule: NonEmptyString,
      killSwitch: { type: "array", items: NonEmptyString },
      unresolved: { type: "array", items: NonEmptyString },
    },
  },
  decision: {
    type: "object",
    additionalProperties: false,
    required: [
      "action",
      "routeTo",
      "ttlSec",
      "hardVeto",
      "executionPolicyRef",
      "decisionBasisRevision",
    ],
    properties: {
      action: { $ref: "#/$defs/verdict" },
      routeTo: { type: "string", enum: ["bangtong", "none"] },
      ttlSec: { type: "integer", minimum: 1 },
      hardVeto: { type: "boolean" },
      executionPolicyRef: NonEmptyString,
      decisionBasisRevision: { type: "integer", minimum: 0 },
    },
  },
  outcome: {
    type: "object",
    additionalProperties: false,
    required: ["author", "observedAt", "executed", "notes", "decisionBasisRevision"],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      observedAt: NonEmptyString,
      executed: { type: "boolean" },
      resultR: { type: "number" },
      maxDrawdownR: { type: "number" },
      thesisScore: Score01,
      antithesisScore: Score01,
      synthesisScore: Score01,
      notes: NonEmptyString,
      decisionBasisRevision: { type: "integer", minimum: 0 },
    },
  },
} as const;

export const TradingDialecticTaskJsonSchema = {
  $id: "tradingDialectic.task.v1",
  $defs: SharedDefs,
  type: "object",
  additionalProperties: false,
  required: ["kind", "version", "taskId", "revision", "state", "meta", "roles", "context"],
  properties: {
    kind: { const: TRADING_DIALECTIC_KIND },
    version: { const: TRADING_DIALECTIC_VERSION },
    taskId: NonEmptyString,
    revision: { type: "integer", minimum: 0 },
    state: {
      type: "string",
      enum: [
        "OPEN",
        "THESIS_SUBMITTED",
        "ANTITHESIS_SUBMITTED",
        "REBUTTAL_SUBMITTED",
        "WAITING_TRIGGER",
        "EXECUTION_ROUTED",
        "ABSTAINED",
        "VETOED",
        "SETTLED",
        "EXPIRED",
        "CANCELLED",
        "FAILED",
      ],
    },
    meta: { $ref: "#/$defs/meta" },
    roles: {
      type: "object",
      additionalProperties: false,
      required: ["thesisAgent", "antithesisAgent", "synthAgent"],
      properties: {
        thesisAgent: { $ref: "#/$defs/agentRef" },
        antithesisAgent: { $ref: "#/$defs/agentRef" },
        synthAgent: { $ref: "#/$defs/agentRef" },
      },
    },
    context: { $ref: "#/$defs/context" },
    thesis: { $ref: "#/$defs/thesis" },
    antithesis: { $ref: "#/$defs/antithesis" },
    rebuttal: { $ref: "#/$defs/rebuttal" },
    synthesis: { $ref: "#/$defs/synthesis" },
    decision: { $ref: "#/$defs/decision" },
    outcome: { $ref: "#/$defs/outcome" },
  },
} as const;

export const TradingDialecticTaskInputJsonSchema = {
  $id: "tradingDialectic.taskInput.v1",
  $defs: SharedDefs,
  type: "object",
  additionalProperties: false,
  required: ["contract"],
  properties: {
    contract: {
      type: "object",
      additionalProperties: false,
      required: ["kind", "version", "phase", "task"],
      properties: {
        kind: { const: TRADING_DIALECTIC_KIND },
        version: { const: TRADING_DIALECTIC_VERSION },
        phase: {
          type: "string",
          enum: ["thesis", "antithesis", "rebuttal", "synthesis", "outcome"],
        },
        task: TradingDialecticTaskJsonSchema,
      },
    },
  },
} as const;

export const TradingDialecticExpectedOutputJsonSchemas = {
  "tradingDialectic.thesis.v1": {
    $id: "tradingDialectic.thesis.v1",
    $defs: SharedDefs,
    ...SharedDefs.thesis,
  },
  "tradingDialectic.antithesis.v1": {
    $id: "tradingDialectic.antithesis.v1",
    $defs: SharedDefs,
    ...SharedDefs.antithesis,
  },
  "tradingDialectic.rebuttal.v1": {
    $id: "tradingDialectic.rebuttal.v1",
    $defs: SharedDefs,
    ...SharedDefs.rebuttal,
  },
  "tradingDialectic.synthesisDecision.v1": {
    $id: "tradingDialectic.synthesisDecision.v1",
    $defs: SharedDefs,
    type: "object",
    additionalProperties: false,
    required: ["author", "submittedAt", "synthesis", "decision"],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      submittedAt: NonEmptyString,
      synthesis: { $ref: "#/$defs/synthesis" },
      decision: { $ref: "#/$defs/decision" },
    },
  },
  "tradingDialectic.outcome.v1": {
    $id: "tradingDialectic.outcome.v1",
    $defs: SharedDefs,
    ...SharedDefs.outcome,
  },
} as const;
